### PR TITLE
Refactor html to render with react

### PR DESCRIPTION
**Pull request by stevenyslee**
@ansonao @wtseng678 @enjik

### CODE REVIEW

**Comment by enjik** [comment]
Did you install eslint? The indentation seems to be off.

**Comment by stevenyslee** [comment]
I've installed esLint on a separate branch that I will merge into the master branch. I'll fix the indentation when I am able to merge in the eslint installation

**Comment by enjik** [comment]
Also, it seems like you are missing a newline in some of your files. Make sure to go through and add these on all your files!

**Review by enjik — APPROVED** [review]
Looks good! eslint should identify most of the syntactical changes I recommended.

**Pull request merged**
